# Generated by Django 5.2.3 on 2025-06-22 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('qna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlikes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='answerlikes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlikes',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='questionlikes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionlikes',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='questionlikes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='asked_by',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='lesson',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qna.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.courses')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qna.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.DeleteModel(
            name='AnswerComments',
        ),
        migrations.DeleteModel(
            name='AnswerLikes',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='QuestionLikes',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
