# Generated by Django 5.1.7 on 2025-06-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=100)),
                ('notice_description', models.TextField()),
                ('notice_issued', models.CharField(max_length=100)),
                ('enrolled_course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
